# user-server-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: user-server-service
  namespace: tarot
spec:
  selector:
    app: user-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
  