# user-server-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: user-server-service
  namespace: neves
spec:
  selector:
    app: user-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP