# email-server-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: email-server-secret
  labels:
    app: email-server
  namespace: tarot
type: Opaque
stringData:
  MAIL_USERNAME: "{{ .Values.emailServer.mailUsername }}"
  MAIL_PASSWORD: "{{ .Values.emailServer.mailPassword }}"