apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-sample-api
  template:
    metadata:
      labels:
        app: my-sample-api
    spec:
      containers:
      - name: api
        image: nginx:latest
        ports:
        - containerPort: 80