apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: neves
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: public.ecr.aws/k8s0f8l3/neves/user_server:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: user-server-config